### ISSUE TITLE
Add Billing organisation and Person ID in user account

### ISSUE THREAD

**Issue by SeoyongLim** [eResearchSA/bman#2]
In order to simplify displaying billing organisation in HPC summary and Allocation summary page, 
if billing organisation id and person id would be placed in user account, it would be great

https://github.com/eResearchSA/bman/blob/master/bman/models/organisation.py#L127

 extended[account.username] = dict(
               fullname=account.role.person.full_name,
               organisation=account.role.organisation.name,
               billing=account.billing_org.id,
               personid=account.role.person.id,
               email=account.role.email)

**Comment by Li-ReDBox** [comment]
The function returns all accounts which have billing relationship with the organisation in question. Does not need this modification to get an account's billing organisation id. See this [line](https://github.com/eResearchSA/bman/blob/master/bman/models/organisation.py#L117).
